# Generated by Django 5.1.2 on 2025-12-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('type', models.CharField(choices=[('security_device', '安全设备'), ('ic_firewall', '工控防火墙'), ('ic_audit', '工控审计'), ('ids', 'IDS'), ('other', '其他')], max_length=30, verbose_name='设备类型')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, verbose_name='管理端口')),
                ('user', models.CharField(default='admin', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(default='tdhx@2017', max_length=200, verbose_name='密码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试设备',
                'verbose_name_plural': '测试设备',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=20, verbose_name='系统类型')),
                ('ssh_user', models.CharField(max_length=100, verbose_name='SSH用户名')),
                ('ssh_password', models.CharField(max_length=200, verbose_name='SSH密码')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试环境',
                'verbose_name_plural': '测试环境',
                'ordering': ['-created_at'],
            },
        ),
    ]
