# Generated by Django 5.1.2 on 2026-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='S7ServerDBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(default='default', max_length=100, verbose_name='服务器ID')),
                ('db_number', models.IntegerField(verbose_name='DB块号')),
                ('data', models.BinaryField(verbose_name='DB数据（二进制）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'S7服务器DB数据',
                'verbose_name_plural': 'S7服务器DB数据',
                'ordering': ['server_id', 'db_number'],
                'indexes': [models.Index(fields=['server_id', 'db_number'], name='main_s7serv_server__670897_idx')],
                'unique_together': {('server_id', 'db_number')},
            },
        ),
    ]
