# Generated by Django 5.1.2 on 2026-01-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_s7serverdbdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('custom_service', '自定义服务'), ('l2_custom_service', '二层自定义服务')], max_length=50, verbose_name='服务类型')),
                ('operation_type', models.CharField(choices=[('add', '新增'), ('edit', '编辑'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('name', models.CharField(help_text='仅支持字母、数字、中文和下划线，最长32字节', max_length=32, verbose_name='名称')),
                ('desc', models.CharField(blank=True, help_text='最长64字节', max_length=64, verbose_name='描述')),
                ('content', models.TextField(help_text='TCP/UDP: 协议类型;端口号;0;0 | ICMP: icmp;0,类型;编码 | 其他: 协议号;0;0;0;', verbose_name='内容')),
                ('expected_success', models.BooleanField(default=True, verbose_name='期望成功')),
                ('expected_response', models.TextField(blank=True, help_text='可选的期望响应内容，用于对比验证', verbose_name='期望响应内容')),
                ('expected_status_code', models.IntegerField(default=200, verbose_name='期望状态码')),
                ('last_test_result', models.BooleanField(blank=True, null=True, verbose_name='最后测试结果')),
                ('last_test_response', models.TextField(blank=True, verbose_name='最后测试响应')),
                ('last_test_status_code', models.IntegerField(blank=True, null=True, verbose_name='最后测试状态码')),
                ('last_test_time', models.DateTimeField(blank=True, null=True, verbose_name='最后测试时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务测试用例',
                'verbose_name_plural': '服务测试用例',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_type', 'operation_type'], name='main_servic_service_2ebcba_idx'), models.Index(fields=['enabled'], name='main_servic_enabled_71be90_idx')],
            },
        ),
    ]
