# Generated by Django 5.1.2 on 2026-01-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_servicetestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetestcase',
            name='is_default',
            field=models.BooleanField(default=False, help_text='默认用例不能删除', verbose_name='是否默认用例'),
        ),
    ]
