# Generated by Django 5.1.2 on 2026-04-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicetestcase_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdevice',
            name='backend_password',
            field=models.CharField(blank=True, default='', help_text='后台root密码，留空则使用设备类型默认密码', max_length=200, verbose_name='后台密码'),
        ),
        migrations.AlterField(
            model_name='testdevice',
            name='password',
            field=models.CharField(blank=True, default='', help_text='SSH登录密码', max_length=200, verbose_name='SSH密码'),
        ),
    ]
