# Generated by Django 5.1.2 on 2026-04-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_backend_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdevice',
            name='is_long_running',
            field=models.BooleanField(default=False, help_text='长跑环境默认启动监测', verbose_name='长跑环境'),
        ),
    ]
